@PORT = 5000
@endPoint = http://localhost:{{PORT}}/api/v1

POST {{endPoint}}/users/register
Content-Type: application/json

{
    "userName" : "prashijan",
    "email" : "prashijan@ram.com",
    "phoneNumber" : 48849,
    "password" : "password"
}

###


GET {{endPoint}}/users


###

POST {{endPoint}}/users/login
Content-Type: application/json

{
"email": "prashijan@ram.com",
"password": "password"
}