@endPoint = http://localhost:3000/api/v1

POST {{endPoint}}/users/register
Content-Type: application/json

{
    "userName" : "harti",
    "email" : "hari@ram.com",
    "phoneNumber" : 234,
    "password" : "password"
}

###


GET {{endPoint}}/users


###

POST {{endPoint}}/users/login
Content-Type: application/json

{
"email": "hari@ram.com",
"password": "password"
}